### ISSUE TITLE
Privacy impact analysis for social media

### ISSUE THREAD

**Issue by jennmalcolm** [DOI-ONRR/doi-extractives-data#3092]
We are required to perform a privacy impact analysis for our social media presence. We need to work with our privacy officer to get that done before we can start posting.

**Comment by mentastc** [comment]
Rich will be coordinating with the Office of Secretary's Privacy Officer regarding the attached in hopes it will facilitate out our PIA requirements.
https://mail.google.com/mail/u/0/?ui=2&ik=99cf791a66&view=att&th=164d83b427fed53d&attid=0.1&disp=inline&realattid=f_jk2zo5kp0&safe=1&zw
https://mail.google.com/mail/u/0/?ui=2&ik=99cf791a66&view=att&th=164d83b427fed53d&attid=0.2&disp=inline&realattid=f_jk2zw7ks1&safe=1&zw
