### ISSUE TITLE
Update designs from user interview findings

### ISSUE THREAD

**Issue by mcharg** [DOI-ONRR/doi-extractives-data#3278]
Home Page
- [x] Implement the version of Home C with more visible tabs.
- [x] Better frame the purpose of the Data Highlights section.
- [x] Add interactivity to Data Highlights.
- [x] Put the map before Data Highlights.
- [x] Revisit the use of links and buttons and icon usage.

Explore Data
- [x] Include the descriptions at the top of the Explore Data page and consider adding them to other pages, as well.
- [x] Use the labeling we have in the production wireframe, but add a description to the top of the page.
- [x] Revisit the use of links and buttons and icon usage.

**Comment by mcharg** [comment]
Updated home page design:
https://1rn7bf.axshare.com/#g=1&p=home_final

@brentryanjohnson to finalize copy.

@master12 When you get to assembling the key facts on the home page, you should use this layout.  I understand that we won't get the interactivity right away, but this is where we want to head.

@jennmalcolm @Maroyafaied @lpgoldstein  @mentastc Any feedback?

Note: I haven't figured out what to do with the tabbed piece on smaller viewports, yet.

**Comment by mcharg** [comment]
I added the description blue boxes and new buttony icons to Explore Data, Production, and Revenue.
Explore Data: https://ug2su1.axshare.com/#g=1&p=explore_data_final
Production: https://ug2su1.axshare.com/#g=1&p=production_final
Revenue: https://ug2su1.axshare.com/#g=1&p=revenue_final

@brentryanjohnson to finalize copy.

@jennmalcolm @Maroyafaied @lpgoldstein @mentastc Any feedback?

**Comment by lpgoldstein** [comment]
Buttons make it easier to find and know something is "clickable"
